### ISSUE TITLE
isBoard already declared

### ISSUE THREAD

**Issue by shiuido** [fatchan/jschan#148] opened 2020-05-30 08:23 UTC
I have completed installation as per instructions on the front page of the project. However I can see there are errors in both chan-error.log and build-worker-error.log. Both have the same syntax error relating to the isBoard variable, which I believe lives in head.pug. I suspect this isn't a problem with head.pug, but is possibly a problem with my environment, but I'm at a loss.

Here you can see an exert of the errors from build-worker-error.log:
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
SyntaxError: Identifier 'isBoard' has already been declared
    at Function (<anonymous>)
    at wrap (/home/admin/jschan/node_modules/pug-runtime/wrap.js:6:10)
    at Object.exports.compile (/home/admin/jschan/node_modules/pug/lib/index.js:287:7)
    at handleTemplateCache (/home/admin/jschan/node_modules/pug/lib/index.js:240:25)
    at Object.exports.renderFile (/home/admin/jschan/node_modules/pug/lib/index.js:452:10)
    at module.exports (/home/admin/jschan/helpers/render.js:14:19)
    at Object.buildHomepage (/home/admin/jschan/helpers/tasks.js:203:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-05-30 08:00:00.175: SyntaxError: Identifier 'isBoard' has already been declared
    at Function (<anonymous>)
    at wrap (/home/admin/jschan/node_modules/pug-runtime/wrap.js:6:10)
    at Object.exports.compile (/home/admin/jschan/node_modules/pug/lib/index.js:287:7)
    at handleTemplateCache (/home/admin/jschan/node_modules/pug/lib/index.js:240:25)
    at Object.exports.renderFile (/home/admin/jschan/node_modules/pug/lib/index.js:452:10)
    at module.exports (/home/admin/jschan/helpers/render.js:14:19)
    at Object.buildHomepage (/home/admin/jschan/helpers/tasks.js:203:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) Promise {
  <rejected> SyntaxError: Identifier 'isBoard' has already been declared
      at Function (<anonymous>)
      at wrap (/home/admin/jschan/node_modules/pug-runtime/wrap.js:6:10)
      at Object.exports.compile (/home/admin/jschan/node_modules/pug/lib/index.js:287:7)
      at handleTemplateCache (/home/admin/jschan/node_modules/pug/lib/index.js:240:25)
      at Object.exports.renderFile (/home/admin/jschan/node_modules/pug/lib/index.js:452:10)
      at module.exports (/home/admin/jschan/helpers/render.js:14:19)
      at Object.buildHomepage (/home/admin/jschan/helpers/tasks.js:203:22)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
}
```

Exert from chan-error.log
```
1|chan  | 2020-05-30 08:20:22.264: SyntaxError: Identifier 'isBoard' has already been declared
1|chan  |     at Function (<anonymous>)
1|chan  |     at wrap (/home/admin/jschan/node_modules/pug-runtime/wrap.js:6:10)
1|chan  |     at Object.exports.compile (/home/admin/jschan/node_modules/pug/lib/index.js:287:7)
1|chan  |     at handleTemplateCache (/home/admin/jschan/node_modules/pug/lib/index.js:240:25)
1|chan  |     at Object.exports.renderFile (/home/admin/jschan/node_modules/pug/lib/index.js:452:10)
1|chan  |     at Object.exports.renderFile (/home/admin/jschan/node_modules/pug/lib/index.js:442:21)
1|chan  |     at View.exports.__express [as engine] (/home/admin/jschan/node_modules/pug/lib/index.js:491:11)
1|chan  |     at View.render (/home/admin/jschan/node_modules/express/lib/view.js:135:8)
1|chan  |     at tryRender (/home/admin/jschan/node_modules/express/lib/application.js:640:10)
1|chan  |     at Function.render (/home/admin/jschan/node_modules/express/lib/application.js:592:
     at ServerResponse.render (/home/admin/jschan/node_modules/express/lib/response.js:1012:7)
1|chan  |     at module.exports (/home/admin/jschan/helpers/dynamic.js:11:14)
1|chan  |     at /home/admin/jschan/server.js:113:10
1|chan  |     at Layer.handle_error (/home/admin/jschan/node_modules/express/lib/router/layer.js:71:5)
1|chan  |     at trim_prefix (/home/admin/jschan/node_modules/express/lib/router/index.js:315:13)
1|chan  |     at /home/admin/jschan/node_modules/express/lib/router/index.js:284:7
1|chan  | 2020-05-30 08:20:24.662: SyntaxError: Identifier 'isBoard' has already been declared
1|chan  |     at Function (<anonymous>)
1|chan  |     at wrap (/home/admin/jschan/node_modules/pug-runtime/wrap.js:6:10)
1|chan  |     at Object.exports.compile (/home/admin/jschan/node_modules/pug/lib/index.js:287:7)
1|chan  |     at handleTemplateCache (/home/admin/jschan/node_modules/pug/lib/index.js:240:25)
1|chan  |     at Object.exports.renderFile (/home/admin/jschan/node_modules/pug/lib/index.js:452:10)
1|chan  |     at module.exports (/home/admin/jschan/helpers/render.js:14:19)
1|chan  |     at buildHomepage (/home/admin/jschan/helpers/tasks.js:203:22)
1|chan  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
1|chan  |     at async module.exports (/home/admin/jschan/models/pages/home.js:9:10)
1|chan  | 2020-05-30 08:20:24.703: SyntaxError: Identifier 'isBoard' has already been declared
1|chan  |     at Function (<anonymous>)
1|chan  |     at wrap (/home/admin/jschan/node_modules/pug-runtime/wrap.js:6:10)
1|chan  |     at Object.exports.compile (/home/admin/jschan/node_modules/pug/lib/index.js:287:7)
1|chan  |     at handleTemplateCache (/home/admin/jschan/node_modules/pug/lib/index.js:240:25)
1|chan  |     at Object.exports.renderFile (/home/admin/jschan/node_modules/pug/lib/index.js:452:10)
1|chan  |     at Object.exports.renderFile (/home/admin/jschan/node_modules/pug/lib/index.js:442:21)
1|chan  |     at View.exports.__express [as engine] (/home/admin/jschan/node_modules/pug/lib/index.js:491:11)
1|chan  |     at View.render (/home/admin/jschan/node_modules/express/lib/view.js:135:8)
1|chan  |     at tryRender (/home/admin/jschan/node_modules/express/lib/application.js:640:10)
1|chan  |     at Function.render (/home/admin/jschan/node_modules/express/lib/application.js:592:3)
1|chan  |     at ServerResponse.render (/home/admin/jschan/node_modules/express/lib/response.js:1012:7)
1|chan  |     at module.exports (/home/admin/jschan/helpers/dynamic.js:11:14)
1|chan  |     at /home/admin/jschan/server.js:113:10
1|chan  |     at Layer.handle_error (/home/admin/jschan/node_modules/express/lib/router/layer.js:71:5)
1|chan  |     at trim_prefix (/home/admin/jschan/node_modules/express/lib/router/index.js:315:13)
1|chan  |     at /home/admin/jschan/node_modules/express/lib/router/index.js:284:7
```

**Comment by shiuido** [comment] 2020-05-30 12:23
To reproduce: follow the Setup instructions from a fresh install of Debian 9.5 (Linux 4.9.0-8-amd64).

**Comment by fatchan** [comment] 2020-05-30 13:02
This was caused by a regression in a dependency, see similar issue: https://github.com/pugjs/pug/issues/3260
I updated package-lock.json on dev branch. Pull and run `npm install` again and it should be fixed.

**Closed by fatchan** 2020-05-30 13:02 UTC
Labels: Need repro steps
